version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "9000:9000"

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: inventario2
      MYSQL_ROOT_PASSWORD: root
    tmpfs:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
