services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - vendor_data:/var/www/vendor
      - storage_data:/var/www/storage
      - bootstrap_cache:/var/www/bootstrap/cache
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inventario2
      MYSQL_ROOT_PASSWORD: root
    
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  vendor_data:
  storage_data:
  bootstrap_cache:
